# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bcdc4fa31fe8df365cdc54d59d22e9e085ff1dfcce18c638ebcec9347afbec01a1032f8f89746b8fcbc6fcaf2c237193153bf25fcb1772368a1dc51715d00c31

test:
  secret_key_base: 86a28ecde93ef37b5e725e3bda5337ac162e7efe6e7f0d6cb91ba95dcae470b01ab6d89b0d7920ba9726cda1008d86286467869c9d4de6c5588c20cf32998365

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
